// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sadhcshdyjfpbaylkwab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZGhjc2hkeWpmcGJheWxrd2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTUzNzksImV4cCI6MjA2NDk3MTM3OX0.y29xmladH4taabJSGwnQoejAB9KjPPbNk6Uyq62Bjvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);